#!/usr/bin/env bash
# setup_env.sh
# Detects the current platform and writes a .env file with the correct
# value for DOCKER_GID.
#
# Run once before `docker compose up`:
#   bash setup_env.sh
set -euo pipefail

ENV_FILE=".env"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_VARS_FILE="${SCRIPT_DIR}/../Terraform/variables.tf"

# Extract the default value of a Terraform variable block.
tf_default() {
  local var_name="$1"
  awk -v vname="$var_name" '
    $0 ~ "^variable \"" vname "\"" { in_block=1; next }
    in_block && /default/ {
      gsub(/.*default[[:space:]]*=[[:space:]]*"?/, "")
      gsub(/"[[:space:]]*$/, "")
      gsub(/[[:space:]]*$/, "")
      print; exit
    }
    in_block && /^\}/ { in_block=0 }
  ' "$TF_VARS_FILE"
}

# ── Detect platform ───────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)
    # Native Linux or WSL2 — read the actual GID of the Docker socket.
    # The Airflow containers are added to this group so they can access
    # /var/run/docker.sock without running as root.
    DOCKER_GID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || echo 0)"
    echo "[setup_env] Platform: Linux/WSL  |  DOCKER_GID=${DOCKER_GID}"
    ;;
  Darwin*)
    # macOS Docker Desktop — socket is a proxy, GID not needed.
    DOCKER_GID="0"
    echo "[setup_env] Platform: macOS  |  DOCKER_GID=${DOCKER_GID}"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    # Windows Git Bash / WSL1 fallback
    DOCKER_GID="0"
    echo "[setup_env] Platform: Windows  |  DOCKER_GID=${DOCKER_GID}"
    ;;
  *)
    echo "[setup_env] Unknown platform '$OS', using safe defaults."
    DOCKER_GID="0"
    ;;
esac

# ── Extract Airflow variable values from variables.tf ─────────────────────────
if [[ -f "$TF_VARS_FILE" ]]; then
  BQ_PROJECT="$(tf_default project)"
  BQ_DATASET="$(tf_default bq_dataset_name)"
  GCS_BUCKET="$(tf_default gcs_bucket_name)"
  echo "[setup_env] Extracted Airflow variables from variables.tf"
else
  echo "[setup_env] WARNING: variables.tf not found at ${TF_VARS_FILE} — Airflow variables will be empty."
  BQ_PROJECT=""
  BQ_DATASET=""
  GCS_BUCKET=""
fi

# ── Stage credentials for the Docker volume ───────────────────────────────────
# Reads the `credentials` path from variables.tf and copies the key file to
# Terraform/service_account.json — the fixed path expected by the
# credentials_loader service in docker-compose.yml.
# This allows any filename/path to be used on Linux/macOS; Windows users still
# need to place the file manually as service_account.json.
if [[ -f "$TF_VARS_FILE" ]]; then
  TF_DIR="${SCRIPT_DIR}/../Terraform"
  CREDENTIALS_SRC="$(tf_default credentials)"

  # Resolve relative paths against the Terraform directory
  if [[ "$CREDENTIALS_SRC" != /* ]]; then
    CREDENTIALS_SRC="${TF_DIR}/${CREDENTIALS_SRC}"
  fi

  CREDENTIALS_DEST="${TF_DIR}/service_account.json"

  # Docker creates the bind-mount target as a directory when the file doesn't
  # exist yet. Remove it so cp can write a file there instead.
  if [[ -d "$CREDENTIALS_DEST" ]]; then
    rm -rf "$CREDENTIALS_DEST"
    echo "[setup_env] Removed stale directory at Terraform/service_account.json (created by Docker)."
  fi

  if [[ -f "$CREDENTIALS_SRC" ]]; then
    if [[ "$CREDENTIALS_SRC" -ef "$CREDENTIALS_DEST" ]]; then
      echo "[setup_env] Credentials already at Terraform/service_account.json — skipping copy."
    else
      cp "$CREDENTIALS_SRC" "$CREDENTIALS_DEST"
      echo "[setup_env] Staged credentials: $(basename "$CREDENTIALS_SRC") → Terraform/service_account.json"
    fi
  else
    echo "[setup_env] WARNING: credentials file not found at '${CREDENTIALS_SRC}'"
    echo "[setup_env]          Update the 'credentials' default in Terraform/variables.tf."
  fi
fi

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup_env.sh — do not edit manually.
# Re-run setup_env.sh if you change machines or platforms.

# GID of /var/run/docker.sock on the host.
# Added to Airflow containers via group_add so DockerOperator can connect
# to the socket on Linux/WSL without running as root.
DOCKER_GID=${DOCKER_GID}

# Airflow variables sourced from Terraform/variables.tf.
# GCP credentials are loaded into the Docker volume via the credentials_loader
# setup profile and are always available at /data/service_account.json.
BQ_PROJECT=${BQ_PROJECT}
BQ_DATASET=${BQ_DATASET}
GCS_BUCKET=${GCS_BUCKET}
ENVEOF

echo "[setup_env] Written ${ENV_FILE}."
echo "[setup_env] You can now run: docker compose --profile setup up -d"