# setup_env.ps1
# Windows equivalent of setup_env.sh
$ErrorActionPreference = "Stop"

$EnvFile = ".env"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$TfVarsFile = Join-Path $ScriptDir "..\Terraform\variables.tf"

function Get-TfDefault {
    param (
        [string]$VarName
    )
    if (!(Test-Path $TfVarsFile)) {
        return ""
    }
    $content = Get-Content $TfVarsFile -Raw
    $pattern = "variable\s+`"$VarName`"\s*\{([\s\S]*?)\}"
    $match = [regex]::Match($content, $pattern)
    if ($match.Success) {
        $block = $match.Groups[1].Value
        $defaultMatch = [regex]::Match($block, "default\s*=\s*`"?(.*?)`"\s*(\r?\n|$)")
        if ($defaultMatch.Success) {
            return $defaultMatch.Groups[1].Value.Trim()
        }
    }
    return ""
}

# ── Platform detection ─────────────────────────────
$os = $env:OS
if ($env:WSL_DISTRO_NAME) {
    $dockerGid = 0
    Write-Host "[setup_env] WSL detected"
}
elseif ($os -match "Windows") {
    $dockerGid = 0
    Write-Host "[setup_env] Windows detected"
}
else {
    $dockerGid = 0
    Write-Host "[setup_env] Unknown OS"
}

# ── Extract Terraform defaults ─────────────────────
$bqProject = Get-TfDefault "project"
$bqDataset = Get-TfDefault "bq_dataset_name"
$gcsBucket = Get-TfDefault "gcs_bucket_name"
Write-Host "[setup_env] Extracted variables from variables.tf"

# ── Write .env ─────────────────────────────────────
@"
# Auto-generated by setup_env.ps1 — do not edit manually.
# Re-run setup_env.ps1 if you change machines or platforms.

# GID of /var/run/docker.sock on the host.
# Added to Airflow containers via group_add so DockerOperator can connect
# to the socket on Linux/WSL without running as root.
DOCKER_GID=$dockerGid

# Airflow variables sourced from Terraform/variables.tf.
# GCP credentials are loaded into the Docker volume via the credentials_loader
# setup profile and are always available at /data/service_account.json.
BQ_PROJECT=$bqProject
BQ_DATASET=$bqDataset
GCS_BUCKET=$gcsBucket
"@ | Set-Content $EnvFile -Encoding UTF8

Write-Host "[setup_env] .env written successfully."
Write-Host "[setup_env] You can now run: docker compose --profile setup up -d"