#!/usr/bin/env bash
# setup_env.sh
# Detects the current platform and writes a .env file with the correct
# values for DOCKER_GID and PGHOST.
#
#
# Run once before `docker compose up`:
#   bash setup_env.sh
set -euo pipefail

ENV_FILE=".env"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_VARS_FILE="${SCRIPT_DIR}/../Terraform/variables.tf"

# Extract the default value of a Terraform variable block.
tf_default() {
  local var_name="$1"
  awk -v vname="$var_name" '
    $0 ~ "^variable \"" vname "\"" { in_block=1; next }
    in_block && /default/ {
      gsub(/.*default[[:space:]]*=[[:space:]]*"?/, "")
      gsub(/"[[:space:]]*$/, "")
      gsub(/[[:space:]]*$/, "")
      print; exit
    }
    in_block && /^\}/ { in_block=0 }
  ' "$TF_VARS_FILE"
}

# ── Detect platform ───────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux*)
    # Native Linux or WSL2 — read the actual GID of the Docker socket.
    # The Airflow containers are added to this group so they can access
    # /var/run/docker.sock without running as root.
    DOCKER_GID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || echo 0)"
    # On Linux the DockerOperator containers join accidents_net, so they
    # can reach pgdatabase by its service name directly.
    PGHOST="pgdatabase"
    echo "[setup_env] Platform: Linux/WSL  |  DOCKER_GID=${DOCKER_GID}  |  PGHOST=${PGHOST}"
    ;;
  Darwin*)
    # macOS Docker Desktop — socket is a proxy, GID not needed.
    DOCKER_GID="0"
    # host.docker.internal resolves to the Docker Desktop host on Mac.
    PGHOST="host.docker.internal"
    echo "[setup_env] Platform: macOS  |  DOCKER_GID=${DOCKER_GID}  |  PGHOST=${PGHOST}"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    # Windows Git Bash / WSL1 fallback
    DOCKER_GID="0"
    PGHOST="host.docker.internal"
    echo "[setup_env] Platform: Windows  |  DOCKER_GID=${DOCKER_GID}  |  PGHOST=${PGHOST}"
    ;;
  *)
    echo "[setup_env] Unknown platform '$OS', using safe defaults."
    DOCKER_GID="0"
    PGHOST="host.docker.internal"
    ;;
esac

# ── Extract Airflow variable values from variables.tf ─────────────────────────
if [[ -f "$TF_VARS_FILE" ]]; then
  BQ_PROJECT="$(tf_default project)"
  BQ_DATASET="$(tf_default bq_dataset_name)"
  GCS_BUCKET="$(tf_default gcs_bucket_name)"
  echo "[setup_env] Extracted Airflow variables from variables.tf"
else
  echo "[setup_env] WARNING: variables.tf not found at ${TF_VARS_FILE} — Airflow variables will be empty."
  BQ_PROJECT=""
  BQ_DATASET=""
  GCS_BUCKET=""
fi

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by setup_env.sh — do not edit manually.
# Re-run setup_env.sh if you change machines or platforms.

# GID of /var/run/docker.sock on the host.
# Added to Airflow containers via group_add so DockerOperator can connect
# to the socket on Linux/WSL without running as root.
DOCKER_GID=${DOCKER_GID}

# Postgres hostname used by DockerOperator task containers.
# - Linux/WSL:    pgdatabase  (task containers join accidents_net)
# - Windows/Mac:  host.docker.internal  (Docker Desktop proxy)
PGHOST=${PGHOST}

# Airflow variables sourced from Terraform/variables.tf.
# GCP credentials are loaded into the Docker volume via the credentials_loader
# setup profile and are always available at /data/service_account.json.
BQ_PROJECT=${BQ_PROJECT}
BQ_DATASET=${BQ_DATASET}
GCS_BUCKET=${GCS_BUCKET}
ENVEOF

echo "[setup_env] Written ${ENV_FILE}."
echo "[setup_env] You can now run: docker compose --profile setup up -d"